# The protocol. This is used to construct the url for the link that appears in
# email notifications
protocol: https

# The host name. This is used to construct the url for the link that appears in
# email notifications
host: openmind.scribesoftware.com

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 443

# The email address of the administrator. This email will be used as the "from"
# address in emails sent by openmind.
admin_email: openmind@scribesoftware.com

# The subject prefix. This will be the prefix in the subject for emails sent by 
# openmind. For example, "OpenMind: Your new account has been created..."
email_subject_prefix: OpenMind

# The number of minutes until a vote can no longer be rescinded
rescind_minutes: 240

# The default number of days before allocations expire
allocation_expiration_days: 120

# The url to the directory where the images for emails are stored
email_image_url: https://openmind.scribesoftware.com/themes/scribe-new/images/email

# The name of the theme (e.g., skin). This should correspond to a directory 
# under the public/themes directory
app_theme: scribe-new

# The number of days within which to warn the user of unused allocations
# about to expire. A value of 0 means never warn the user.
allocation_expiration_warning_days: 45

# The default timezone for new users. Hint: execute the command:
#     rake time:zones:local
# to get a list of timezones local to your location
default_user_timezone: Eastern Time (US & Canada)

# Max file upload size for non-prodmgr and non-sysadmin users (in KB)
max_file_upload_size: 500

# The number of minutes to wait before, when an idea is created, sending a
# reminder to the author of an idea to vote if they have not already done so. 
# A value of -1 signifies no reminder should be sent
minutes_to_send_vote_reminder: 60

# The number of minutes to wait for a periodic job to complete. If the job does
# not complete in this timeframe, OpenMind will assume it is dead and initiate
# a recovery
periodic_job_timeout: 30

# URL of the corporate web site (which the banner will redirect to)
main_site_url: http://www.scribesoft.com

# A list of release status, separated by commas, within parens, that should be considered GA 
# releases
released_release_statuses: (Released)

# The email address for support.
support_email: support@scribesoft.com

# The email address for sales.
sales_email: sales@scribesoft.com

# A list of enterprise type lookup codes, separated by commas, within parens, that should be considered GA
show_portal_for_enterprise_types: (Scribe,Demo,Authorized Reseller,Certified,Elite)

# Allow the user to manually enter their portal user for the following enterprise types
# A list of enterprise type lookup codes, separated by commas, within parens, that should be considered GA
allow_email_override_for_enterprise_types: (Scribe)


# Can new enterprises view the portal by default? Valid values are "Y" or "N" (without quotes)
new_enterprises_view_portal_default: Y

# A list of enterprise type lookup codes, separated by commas, within parens, for which member users
# will be presented with navigation options to view forum entries
show_metrics_for_enterprise_types: (Scribe)

# Enter the name of the proudct which other products depend up. If you specify a value here,
# the compatibility tab under roadmap menu will be displayed, with compatibility reflected
# in relationship to this product
root_compatibility_product: Insight

# If using one time passwords for single sign on support, this value is the number of seconds from
# now for which the one time password is valid
otp_expire_seconds: 60

# If you are using one time passwords for single sign on support, specify a regular express
# used to match ip addresses which are allowed to request a one time password
otp_trusted_sites: 71\.184\.232\.107|75\.150\.98\.197|65\.52\.0\..*|65\.52\..*\..*

# List of products that can be forecasted
forecasted_products: (6,7,8,42,11,12,43)

sprint_standup_time: 600
